workflows:
  android-app:
    name: Bible Quote Widget Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.example.biblequotewidget"
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android app
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
